---
# Install vvmware packages

- name: unwanted packages are removed
  package:
    name: "{{ vvmware_packages_remove }}"
    state: absent
  become: true
  when: vvmware_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ vvmware_packages_repos }}"
    state: "{{ vvmware_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ vvmware_packages_prereq }}"
    state: "{{ vvmware_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ vvmware_packages_install }}"
    state: "{{ vvmware_packages_state }}"
  become: true
