---
# Template configuration files for vvmware

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ vvmware_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - vvmware_enable_selinux
  become: true
